pygments: true
permalink: "/:title"

## Hekyll Configuration ##
overview: true # true/false -- enabling this will add an overview slide at the end of the presentation
overview-data:
  x: 1000  # integer -- set this to the center x point of the overview slide, usually the center of your slide canvas area
  y: 1000  # integer -- set this to the center y point of the overview slide, usually the center of your slide canvas area
  scale: 10  # integer -- set the scale of the overview slide, usually far enough back to fit everything in view